path: C:\Users\user\OneDrive\桌面\trash dataset\dataset
train: C:\Users\user\OneDrive\桌面\trash dataset\dataset\train
val: C:\Users\user\OneDrive\桌面\trash dataset\dataset\val

nc: 4

names:
  0: biological
  1: paper
  2: plastic
  3: trash